### ISSUE TITLE
Is personal plan of chatGPT suitable for this plugin ?

### ISSUE THREAD

**Issue by laTruffe79** [rana01645/CodeGPT-Laravel#1]
Hello, I got phpStorm 2022.3.2, I installed the plugin, copied the api key but there is no answer from chatGPT.

Thanks.

**Comment by rana01645** [comment]
Thanks for reporing.

It might be because of server load from ChatGPT, sometimes the server got overloaded and don't respond to anything. I'll add a UI to show the request update!

I just checked and it's working fine. Can you try again and let me know If its working now?
<img width="604" alt="image" src="https://user-images.githubusercontent.com/16163521/224769185-3619dc9b-c5a6-49a7-aa4d-03540b414a5d.png">

**Comment by rana01645** [comment]
Okay, I just found my PHPStorm version is PhpStorm 2022.3.1, I'm updating it to latest version and will keep you updated!

**Comment by rana01645** [comment]
It's working fine on PhpStorm 2022.3.2, I'm working on the UI update for the request state.

**Comment by laTruffe79** [comment]
Thank you it's a real good idea, ChatGPT will be a good companion in order to improve my productivity

**Comment by laTruffe79** [comment]
I'm using phpstorm  2022.3.3 on macOS 13.2.1 for your information. best regards.

**Comment by rana01645** [comment]
Added Progress UI for request state

https://github.com/rana01645/CodeGPT-Laravel/commit/394ffafc3ac4d95af5184fd1b48357394b0f44f1
